### ISSUE TITLE
Storing scripts within areas instead ~/Scripts folder

### ISSUE THREAD

**Issue by philipooo** [vtfuture/RequireJSDotNet#38]
Hi
It would be cool if there was a way to store the scripts within an MVC Area so they are more in context. For example:

![2014-09-12_101546](https://cloud.githubusercontent.com/assets/1702399/4247089/14b5eaf8-3a55-11e4-8f1d-78312e051554.png)

Cheers
Philip

**Comment by CezarCretu** [comment]
Please update to 2.1 and check [this](https://github.com/vtfuture/RequireJSDotNet/wiki/Overriding-entry-point-path-generation) out. Let me know if you managed to get it working.

**Comment by philipooo** [comment]
Hi

Thank you. Works for me! Here is my current implementation.
https://gist.github.com/philipooo/2aea22f1ff64182e7a7b

Cheers

**Comment by stefanprodan** [comment]
Very nice @philipooo, I'll reference you're gist in the docs. Thanks

**Comment by philipooo** [comment]
Feel free to reference. I also updated the gist formatting.
