### ISSUE TITLE
Make DefaultEntryPointResolver.Resolve virtual

### ISSUE THREAD

**Issue by maboivin** [vtfuture/RequireJSDotNet#53]
In the DefaultEntryPointResolver implementation, the Resolve method has a nice algorithm to find an entry point.

What I'd like to do is inherit from DefaultEntryPointResolver and based on the condition viewContext.HttpContext.IsDebuggingEnabled, I'd like to change the result to be a minified entry point (add .min in the name of the javascript file if it exists).

Rigth now, the method is not virtual and I don't want to copy the logic as it may change in future versions. By making it virtual, all I have to do is call the base method and add my logic in the overridden method.

If you feel like it could be useful to other people, it could be another implementation that is provided by RequireJS.Net.

**Comment by stefanprodan** [comment]
Please share your .min implementation as a gist or fork, could be useful for others. 
Thanks
