### ISSUE TITLE
EntryPoint override is broken

### ISSUE THREAD

**Issue by kawazoe** [vtfuture/RequireJSDotNet#55]
Context
----------
I am trying to setup RequireJsDoNet in an hybrid ASP.NET MVC / AngularJs application based on the structure [described in this video](https://www.youtube.com/watch?v=f67PFtrldGQ).

I have a project with the following structure:
  - App (Contains all first party, requirejs dependencies)
    - controllers
      - root
        - home
          - FooBar.js (Handles angular bootstraping)
    - root
      - foobar
        - app.js (The actual angular application code)
  - Scripts (Contains all large third party libraries)
    - angular.js
    - jquery.js
    - moment.js
  - Controllers
    - HomeController.cs
      - [GET] FooBar
  - Views
    - Home
      - FooBar.cshtml

I am trying to use the App folder as my requirejs root directory. I expect everything in the Scripts folder to be ignored. I hit two issues when doing this.

Different behavior when using EntryPointRoot
---------------------------------------------------------

The first thing I did was to change my RequireRenderConfiguration instance to this:

```CS
new RequireRendererConfiguration
{
    RequireJsUrl = Url.Content("~/Scripts/require.js"),
    BaseUrl = Url.Content("~/App/"),
    ConfigurationFiles = new[] { "~/requirejs.json" },
    EntryPointRoot = "",
    LoadOverrides = false,
    LocaleSelector = html => System.Threading.Thread.CurrentThread.CurrentUICulture.Name.Split('-')[0]
}
```

Trying to set the `EntryPointRoot` to match the BaseUrl like you do in your samples prevents requirejs from loading the controller file. It generates the following code.

```HTML
<script>
require(["/App/controllers/root/home/FooBar"]);
</script>

<!-- RequireJS generates this script tag -->
<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="/App/controllers/root/home/FooBar" src="/App/controllers/root/home/FooBar"></script>

GET http://localhost:57109/App/controllers/root/home/FooBar
404 Not Found
```

As you can see, the "/App/" prefix shouldn't be there; it isn't when using the "~/Scripts/" EntryPointRoot and BaseUrl. Building a similar require call in the debug console without this prefix loads the file as expected.

AutoBundles compilation task
-------------------------------------

The second issue I have comes when dealing with the compilation task. When setting the `EntryPointOverride` parameter to `$(MSBuildProjectDirectory)\App`, The controllers modules are bundled with their name prefixed with "../app".

Using this requirejs.json auto-bundle:
```JSON
"property": {
  "outputPath": "App/Bundles/",
  "include": [
    { "directory": "controllers/root/foobar" },
    { "directory": "root/foobar" }
  ]
}
```

The following override is generated:
```JSON
"property": {
  "paths": {
    "../app/controllers/root/home/FooBar": "../app/bundles/foobar",
    "../app/root/foobar/app": "../app/bundles/foobar",
  },
  "bundledScripts": [
    "../app/controllers/root/home/FooBar",
    "../app/root/foobar/_app",
  ]
}
```

I also noticed that all bundle name folders  like `viewModels` gets converted to lowercase which prevents dependency injection from working as it is case sensitives.

Close
-------

I have taken a look at the compiler code and I am not really sure of how the entry point override feature works as the original entry point is still used in many places around the code. Am I misunderstanding how this feature is supposed to work or is this really a major issue?

**Comment by davidsk** [comment]
According to your directory listing, you do not have an index.js file there, just a foobar.js.  The javascript file in the contollers/root/home directory should match the action method of your controller which in this case seems to be Index.

Can you try renaming either the Controller method or the javascript file such that they match?  That should allow req

**Comment by kawazoe** [comment]
I don't have an index action in my controller.

**Comment by davidsk** [comment]
Okay, I think I understand.  The BaseUrl is set to app and expects module names / paths that are relative to the app folder but RequireJsDotNet is generating module names / paths that include the app.

The DefaultEntryPointResolver checks that the entryPoint isn't the same as the "~/Scripts" assuming that this is the baseUrl.  It should check that the entryPoint is the same as baseUrl.

I've submitted a pull request (https://github.com/vtfuture/RequireJSDotNet/pull/56) to fix this.  In the meantime, setting your entryPointRoot as '../App/' should work.

**Comment by CezarCretu** [comment]
Thanks @kawazoe for the detailed report and @davidsk for the pull request.
Please check with v 2.1.50 if both of your issues are resolved.

**Comment by kawazoe** [comment]
Sorry for the delay, I just checked it and it looks fine to me.
