### ISSUE TITLE
Relative included file paths not resolved properly  

### ISSUE THREAD

**Issue by papergirl** [vtfuture/RequireJSDotNet#61]
Files which are included defines i.e. the following define(["./kendo.core.min"]) are not resolved correctly they get resolved to <drive>:\<projectpath>\<scriptroot>\kendo.core.min.js instead of the correct relative path of 
<drive>:\<projectpath>\<scriptroot>\kendo\kendo.core.min.js

**Comment by Spudbuckets** [comment]
It doesn't seem to work for me still using the pattern you established for shared modules.

Contents of /Scripts/Controllers/Root/Home/Index.ts:
> var module = require("../Shared/child-module");
> //reference to trick typescript into rendering a dependency
> var x = module;

While typescript is happy with this reference compressor can't find the child-module. It thinks the child module is located at /Shared/child-module.js not /Scripts/Controllers/Root/Shared/child-module.js. Requirejs does understand the reference so I can still deploy but I can't use the auto compressor right now.

PS. I am running RequireJsNet version 2.1.52 off nuget and RequireJsNet.Compressior 2.1.36.

**Comment by stefanprodan** [comment]
Fixed in release [2.2](https://github.com/vtfuture/RequireJSDotNet/releases/tag/v2.2.3)

**Comment by jayryemure** [comment]
Having the same exact issue as @Spudbuckets but on version 2.2.3.  It's not resolving paths with ../ properly.

Looking at the [fix]( #62 ) it only fixes paths with ./ and not ../ ?
