### ISSUE TITLE
exclude not taken into account for the autoCompressor 

### ISSUE THREAD

**Issue by Sshnyari** [vtfuture/RequireJSDotNet#65]
This config doesn't work with autobundles :

```
        "include": [
            {
                "directory": "app"
            }
        ]
        "exclude": [
            {
                "directory": "app/folder1"
            },
            {
                "directory": "app/file1"
            }
        ]
```

It processes file1 and folder1 files anyway.

Is it possible to exclude bundle.Includes before processing in the AutoBundleConfigProcessor ParseConfigs function ?

**Comment by stevecooperorg** [comment]
This is a blocker for me, too. I'm using a library (moment.js) which includes code like this;

                require('./locale/' + name);

The compressor can't parse the parameter (fair enough!) but I also can't exclude moment.js from my bundle. I've tried using the same syntax you mention above.

There's another issue [here](https://github.com/vtfuture/RequireJSDotNet/issues/18) from 26 Aug 2014  which seems to implement it but doesn't seem to have been incorporated. I've [raised a pull request](https://github.com/vtfuture/RequireJSDotNet/pull/77) with an implementation of the necessary code, as outlined by @CezarCretu.

**Comment by stefanprodan** [comment]
Thanks for the PR @stevecooperorg 

The fix is available on NuGet RequireJsNet.Compressor v2.2.4

**Comment by stevecooperorg** [comment]
Brilliant. I can get that rolled into our current code. :)
