### ISSUE TITLE
Compressor : ArrayExpression cast exception for angular-couch-potato.js

### ISSUE THREAD

**Issue by Sshnyari** [vtfuture/RequireJSDotNet#66]
An exception is thrown when trying to cast an Identifier to an ArrayExpression with Jint in ProcessDependencyArray (RequireVisitor).
I think that a simple 'as' will do the job
    var depsArray = depsNode.As<ArrayExpression>();
instead of
    var depsArray = depsNode as ArrayExpression;

**Comment by aquamoth** [comment]
Think this os already solved. If not please reopen with a failing example
