### ISSUE TITLE
RequireJSNet requires a matched JS file per MVC View?

### ISSUE THREAD

**Issue by johndubya** [vtfuture/RequireJSDotNet#68]
I have recently been integrating our solution with RequireJSNet, and one significant problem I have run into is that it appears that RequireJSNet **requires** a JS file for every MVC Action.

For instance, I have an action in `Home/About` that is just a simple HTML page that doesn't need any JS. But when I first loaded that page, I noticed that the call to `Html.RenderRequireJsSetup(new RequireRendererConfiguration { @* config here *@ })` in _Layout.cshtml didn't output anything. So when there is no JS file for the About page at `/Scripts/Controllers/root/Home/About.js`, `Html.RenderRequireJsSetup()` literally just blows up and outputs nothing. No config, no call to load my require.js file. But if I add the file `/Scripts/Controllers/root/Home/About.js`, it works normally.

Obviously, the problem with this is that I have many Actions that don't require any custom JS for that page at all, and I'm not going to create blank JS files for all of these Actions.

It appears to me that what needs to happen is if the `EntryPointResolver` looks in all its paths for a corresponding JS file and doesn't find it, there must be a way for it to not include any custom JS file at all. How can I do this? Thanks.

**Comment by davidsk** [comment]
Can you explain the difference between 
> ...outputs nothing. No config, no call to load my require.js file

 and 

> there must be a way for it to not include any JS file at all.

This is, AFAIK, exactly how it's supposed to work - if there isn't a corresponding entrypoint (javascript) file, then there isn't anything to output.

**Comment by johndubya** [comment]
@davidsk, I edited my question, as I meant "custom JS" file - as in a custom JS file _just_ for that one page. I obviously have other general JS files that _are_ used on that page. It's just that certain pages don't require _specific_ JS beyond the general JS.

**Comment by davidsk** [comment]
Okay, I think I understand.  Certain pages don't have any specific (custom) javascript and therefore there is no corresponding "/Scripts/Controllers/root/Home/About.js" or similar file but you do want to include the standard (general) js files.  Do I have that correct?

**Comment by johndubya** [comment]
You got it.

For instance, I have a general _site.js_ file that is included on every page of a website, which does some "bootstrapping" of the site and provides some utility functions and such. That file needs to be loaded on every page. But then on, say, the About page, there is no need for any custom JS file, because it's just a bunch of text. So the _site.js_ file would still need to load, but there are no other custom JS files to load.

Sorry I was unclear at the start.

**Comment by davidsk** [comment]
No problem, now I understand I can try and help.  That said, I still don't think that RequireJsDotNet is at fault - it's basically just an automated mechanism to locate your custom (entrypoint) file based on your route.  The implication is obviously that if there is no custom (entrypoin)t file, then there's nothing for RequireJsDotNet to do.

The easy option, for the given scenario, is to include the site.js file directly into your layout file using a script tag before the `Html.RenderRequireJsSetup`.  That should ensure that it's always available irrespective of whether there is a custom (entrypoint) or not.  It does mean that the site.js file will need to be a) accessible on the global object or b) self contained i.e. isn't referenced by any other scripts.

All of that said, it's pretty common to have a module (unsurprisingly named 'common') that `requires()` all of the common js files, like site.js, that are needed on every page.  There may be value in being able to specify such a module to the `Html.RenderRequireJsSetup`, such that if a custom (entrypoint) file isn't found, then simply require the common module instead...

I'm gonna give this a little more thought but you might be on to something...

**Comment by davidsk** [comment]
Having thought about this a little more, I don't this is an issue.

- You can still add scripts directly to the page (layout or view) using script tags 
- There are options (alternate layouts, sections etc) that allow you to conditionally include or exclude markup i.e `Html.RenderRequireJsSetup(...)` 
- If there isn't a custom (entrypoint) script, RequireJsDotNet / requirejs doesn't know which general scripts to load

I think the solution you're looking for is to include the general scripts directly to your layout page.

**Comment by johndubya** [comment]
Well, originally, part of the reason why we started down the road of using RequireJS is because RequireJS allows fallback paths for JS files. We currently get lots of logged JS errors caused by external JS files that fail to load, and RequireJS allows you to provide a fallback path, in case that happens, to make sure the file will get loaded. Now, sadly, RequireJSNet doesn't allow this, so that is a huge loss. But all the same, it's very beneficial to use a plugin like RequireJS that ensures JS files get loaded before continuing, and you don't get this functionality with just including a <script> tag on the page. That's why we wanted to include _all_ files through RequireJS. I understand if this plugin won't support that, but that's what we were looking for. Thanks for looking into this.

**Comment by davidsk** [comment]
> RequireJS allows fallback paths for JS files...sadly, RequireJSNet doesn't allow this

I can't help with fallback paths, I've never tried.

> it's very beneficial to use a plugin like RequireJS that ensures JS files get loaded before continuing

Completely agree, a major benefit is that all scripts are loaded before you try to use any of them. 

> That's why we wanted to include all files through RequireJS

If you want to load all files through RequireJs then you **_must_** have an entrypoint - it's the entrypoint that specifies which scripts to load.  Perhaps what you're looking for is a _fallback entrypoint_? An entrypoint that a) is used if a route-specific entrypoint can't be found and b) does nothing other than load the general scripts?

**Comment by johndubya** [comment]
Interesting. I must not be thinking in the right paradigm. I have been operating with the understanding you need a kind of "general entrypoint," if you will, then include other plugins as necessary. In other words, I was thinking of having like an _entrypoint.js_ file that loads the JS files my entire site needs (_site.js_, _jquery.js_, _bootstrap.js_, etc.). That always happens. Then, if another custom, per-page JS file needs to be loaded, a separate `require()` statement is called. So you can see how I wasn't thinking the per-page file was an entrypoint, but rather a one-off file only used on that one page. I may need to adjust my thinking if this is not the common way to do this.

**Comment by davidsk** [comment]
Yeah, you have it a little back to front but even so, I think the issue is sound:  RequireJsDotNet would benefit from a means to identify a fallback entrypoint to be used if a specific entrypoint isn't found.

I should have some time available this weekend to have a stab at this.

**Comment by davidsk** [comment]
Wow.  It's way more simple than I thought.  As per the documentation:

> ...the [resolver] collection will be cycled through until it receives a non-null result...

So, just add another resolver that returns your general entrypoint!

I've created a sample app to demonstrate this: [GeneralEntryPoint.zip](https://github.com/vtfuture/RequireJSDotNet/files/170325/GeneralEntryPoint.zip)

There are three entrypoint files: one for home, one for foo/home and a general case.  Requests to /home and foo/home will locate and use their respective entrypoints;everything else will use the general entrypoint.

**Comment by nikolay-borzov** [comment]
It would be great to have an option in `RequireRendererConfiguration` or `RenderRequireJsSetup` to always render 
```html
<script>
var requireConfig = ...
var require = ...
</script>
<script src="/Scripts/require.js"></script>
```

**Comment by aquamoth** [comment]
Latest master branch now supports fallback paths. Ad for other issues @davidsk provided a good solution.
Please reopen or open new issue if there are outstanding questions.
