### ISSUE TITLE
Compressor fails when processing RequireJS calls using errbacks.

### ISSUE THREAD

**Issue by AdamEssenmacher** [vtfuture/RequireJSDotNet#73]
A require() call may include 1 to 3 arguments, with the third being an [errback](http://requirejs.org/docs/api.html#errbacks).

RequireJsNet.Compressor.Parsing.RequireVisitor.ProcessRequireCall throws an exception if a require call includes 3 arguments:
`if (argCount < 1 || argCount > 2)
            {
                throw new Exception("Invalid number of arguments for require() call " + relativeFileName);
            }`

**Comment by aquamoth** [comment]
Ive just implemented support for the shorthand solution of this; http://requirejs.org/docs/api.html#pathsfallbacks

Code available in master branch for now.
Still need the errback functionality?

**Comment by aquamoth** [comment]
Now errbacks are properly supported in master branch.
