### ISSUE TITLE
Install RequireJsNet.ResxToJs using NuGet is not possible

### ISSUE THREAD

**Issue by slgal** [vtfuture/RequireJSDotNet#74]
Hello, I am getting an issue trying to install RequireJsNet.ResxToJs using NuGet.

VS 2015, version of RequireJsNet.ResxToJs 2.0.8

Severity	Code	Description	Project	File	Line	Suppression State
Error		'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.			0	

Screenshot https://gyazo.com/c371ac1d035b22d9af5e72b6a5b353b4

**Comment by stefanprodan** [comment]
I've tested this with the newest version 2.2 and it's working, please try to update NuGet and Vs.NET
