### ISSUE TITLE
Please clarify installation of Compressor

### ISSUE THREAD

**Issue by slgal** [vtfuture/RequireJSDotNet#75]
Hello @stefanprodan, can you please explain why we need to do:

Get from http://requirejsnet.veritech.io/compressor.html

> For the bundling to take place at build, create a folder named .build in your ASP.NET project root and add a file named Compressor.targets with the following content:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="RequireCompressorTask" AssemblyFile="...\packages\RequireJsNet.Compressor.2.2.3\tools\RequireJsNet.Compressor.dll" />
  <ItemGroup>
    <Configs Include="$(_PackageTempDir)\RequireJS.json" />
    <Content Include="RequireJS.json">
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
  <Target Name="RequireJsNetCompressor" AfterTargets="CopyAllFilesToSingleFolderForMsdeploy">
    <RequireCompressorTask 
      LoggingType="Debug" 
      RequireConfigs="@(Configs)" 
      AutoCompressor="true" 
      EncodingType="UTF8" 
      ProjectPath="$(_PackageTempDir)" 
      PackagePath="$(_PackageTempDir)\Scripts\" />
  </Target>
</Project>
```
While installation of Compressor it's automatically add build task
  \packages\RequireJsNet.Compressor.2.2.3\build\RequireJsNet.Compressor.targets

which looks like do the same. It's mistake or I missing something?

Thanks in advance.

**Comment by stefanprodan** [comment]
The tile is "RUN COMPRESSOR FROM MSBUILD ON A BUILD SERVER".

I am using TeamCity for build and it doesn't pick up the targets from `\packages` that's why I've added that section to the docs.

**Comment by slgal** [comment]
Understand, thanks.
