### ISSUE TITLE
using this with typescript rather than javascript - any examples around?

### ISSUE THREAD

**Issue by gregveres** [vtfuture/RequireJSDotNet#79]
Hi

I am trying to figure out how to proper module definition and inclusion with requirejs and typescript. I ran across this project and I like the integration with MVC (which I am using) and the auto bundling feature. However, I am not sure how to adapt this to typescript (which I am also using). 

I saw the fork that @rangp has done, but there is absolutely no documentation. He says his changes are to support typescript so it sounds good but the examples still use javascript. 

So if anybody has an example somewhere that they could share that creates a type script file per controller action that then includes other typescript modules using require, that would be great. 

Thanks
Greg

**Comment by aquamoth** [comment]
Ive recently started doing exactly what you request. While it is working, I have problem with the compressor though so Im trying to put together a PR for that.
Ill see if I can put together a working example too unless someone else does that faster.
Den 11 nov 2016 01:21 skrev gregveres <notifications@github.com>:Hi
I am trying to figure out how to proper module definition and inclusion with requirejs and typescript. I ran across this project and I like the integration with MVC (which I am using) and the auto bundling feature. However, I am not sure how to adapt this to typescript (which I am also using).
I saw the fork that @rangp has done, but there is absolutely no documentation. He says his changes are to support typescript so it sounds good but the examples still use javascript.
So if anybody has an example somewhere that they could share that creates a type script file per controller action that then includes other typescript modules using require, that would be great.
Thanks
Greg

**Comment by rangp** [comment]
I forked the original requirejsdotnet project for use in the company I'm
working for. We are actively using it with typescript and autobundling for
almost a year now on our production websites and it runs stable. However I
didn't have the time or motivation yet to document my work. However I could
compile an example project with typescript and maybe write a short
documentation on the weekend since it's the first time anyone is asking for
it.

I also developed a version that runs with dotnet core but this one doesn't
have the autobundling feature.

Best regards
Peter

**Comment by gregveres** [comment]
I would very much appreciate an example @rangp and @aquamoth.

Thank you!

**Comment by gregveres** [comment]
HI @rangp 

I understand available time is limited. A simple example project using typescript would be a great starting point. 

Thanks again
Greg

**Comment by aquamoth** [comment]
I've taken the time to write a comprehensive tutorial on setting up RequireJS.Net, including TypeScript. Please check it out at https://github.com/aquamoth/RequireJSDotNet/wiki/Getting-Started and give feedback; Good or bad are welcome alike.

**Comment by gregveres** [comment]
Hi @aquamoth 

That is a good getting-started guide. Thanks for taking the time to write it. I don't really have anything to add at this point. I think it would have helped a lot back in November when I was first tackling all of this, so hopefully it will help other new comers. 

I guess the only other suggestion would be to create git hub project for the sample that you created (if you created one.) I find that even if the guide seems trivial it is sometimes helpful if I can download the entire project and code. 

Greg

**Comment by aquamoth** [comment]
Good point to publish the tutorial and make references to it. 
[I've published the tutorial code here](https://github.com/aquamoth/RequireJS.Net-GettingStarted) and updated the tutorial with references.
