### ISSUE TITLE
Does RequireJS.json get deployed to the server? 

### ISSUE THREAD

**Issue by gregveres** [vtfuture/RequireJSDotNet#85]
Hi @davidsk , @CezarCretu @stefanprodan 

I am have my project working locally with RequireJSNet. I just deployed it to our test server for the first time and I got an error from the server saying that it couldn't find RequireJS.json in the wwwroot. Does this file need to get deployed to the server?  It appears that way because the part of the code that was requesting it was RequireJsNet.Helpers.PathHelpers.VerifyFileExists()

On the assumption that it was needed, I was about to change the Build Action to "content" to get it put on the server, but the build action is already set to RequireJsNetConfig. 

is there a special something that needs to happen to have this file deployed? 

Thanks
Greg

**Comment by gregveres** [comment]
Since nobody has answered, I pursued figuring out how to get RequireJS.json deployed. I am not sure why everybody isn't running into this. Maybe they are and everybody just goes ahead and changes the configuration to deploy this file as a custom deployed file. 

Well that's what I did. I followed this [article](https://www.asp.net/mvc/overview/deployment/visual-studio-web-deployment/deploying-extra-files) and ended up putting the configuration at the end of the csproj file since I need the file deployed in every publish specification. 

If I am doing something wrong, please let me know. For now this is working. 

I don't consider the issue closed because I would have expected the RequireJSNetConfig build action to automatically mark this file for deployment.

**Comment by stefanprodan** [comment]
I've described the steps required to build and deploy in the documentation site [here](http://requirejsnet.veritech.io/compressor.html), check out the build server section.

**Comment by gregveres** [comment]
@stefanprodan 

Ok that must be what I was doing wrong. I am approaching this in steps. The first step was to get requireJS working without i18n and without bundling so I hadn't looked at the bundling step yet. 

Thanks for pointing me in that direction. Maybe I will look at bundling now and then come back for i18n. 

Greg
