### ISSUE TITLE
Cache busting support

### ISSUE THREAD

**Issue by mgboston** [vtfuture/RequireJSDotNet#91]
I have 2 issues I've encountered and I'm hoping someone has an answer that will help me overcome the issues.

1.  I am currently setting the UrlArgs to the app version that is demonstrated in the help.  Is it possible to provide a list of modules that I would like to exclude the UrlArgs from?  For example, I am loading 3rd party libraries from CDN's and I don't want them having the cache busting query string at the end.

2.  Is it possible to make the UrlArgs a file hash based on the contents in the files/bundles rather than the appversion?

**Comment by aquamoth** [comment]
1. `urlArgs` is a property of RequireJS itself. For details see http://requirejs.org/docs/api.html#config-urlArgs. As you can read, from v2.2.0 this can be a javascript function, so you could store a list of files to cache-bust and return an empty string for all others.

2. This was what I wanted to do too initially. My conclusion was it would just take up a lot of cpu cycles to calculate something for the off-chance I ever deploy twice without recompiling first. A determined a better solution is to always return the current clock ticks during development and the compiled version during production.

I hope that somewhat generic answer puts you on the right track!
