### ISSUE TITLE
How can I handle a common JS function for all controllers and actions?

### ISSUE THREAD

**Issue by winsonet** [vtfuture/RequireJSDotNet#96]
I created a main.js(or module) file for all pages, in some pages, just need to run this main.js and there is no other js functions, so I don't 
want to create a js file for this page(or action), for example:

ASP.NET Controller:
Home -- controller
	----Index 	-- action
	----About	-- action

JS script:
/Scripts/
	--Controllers
		----Home
			-------index.js
		----Common
			-----main.js

in Home-About action, I just need to run the common main.js, so I don't want to create the Home-about.js file, how can I do that?

because for this case, if I create the about.js, then this file will be empty and only just need to require the main.js in it, if there are many of these case, then I need to create a lot of empty js files and just for require the same common file, so I don't want to do that.

thanks!

**Comment by davidsk** [comment]
This sounds very similar to #68 and I think the solution is the same.  You should create a generic entrypoint file that specifies your main.js module as a dependency.  The trick is to then add _another_ EntryPointResolver that will return this file.  The advantage here is that every route will automatically be provided your generic entrypoint _unless_ a specific entrypoint is available.

Have a look at  [https://github.com/vtfuture/RequireJSDotNet/files/170325/GeneralEntryPoint.zip](url)

**Comment by winsonet** [comment]
oh, this is what I need, thank you so much!!!
